export type MockSong = {
  id: number;
  nickname: string;
  youtubeUrl: string;
  comment: string;
  thumbnailUrl: string;
  title: string;
  votes?: number;
  voters?: string[];
  createdAt?: string;
  updatedAt?: string;
  timeSlot: number;
  timeMinute?: number;
  timeReason: string;
};

export const mockSongs: MockSong[] = [
  {
    id: 301,
    nickname: "haze",
    youtubeUrl: "https://www.youtube.com/watch?v=5qap5aO4i9A",
    comment: "하루가 다 끝난 줄 알았는데 아직 마음이 조금 깨어 있을 때, 조용히 숨 고르듯 틀어두고 싶은 곡이에요.",
    thumbnailUrl: "https://i.ytimg.com/vi/5qap5aO4i9A/hqdefault.jpg",
    title: "lofi hip hop radio",
    votes: 14,
    voters: [],
    createdAt: "2026-04-01T00:30:00.000Z",
    timeSlot: 0,
    timeReason: "하루가 완전히 꺼지고 생각만 작게 켜지는 시간이라서.",
  },
  {
    id: 302,
    nickname: "mira",
    youtubeUrl: "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    comment: "새벽 작업이 길어질 때 틀어두면 방 안에 작은 불빛이 하나 더 켜진 것 같아서 덜 외로워져요.",
    thumbnailUrl: "https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg",
    title: "beats to relax/study to",
    votes: 9,
    voters: [],
    createdAt: "2026-04-01T02:10:00.000Z",
    timeSlot: 2,
    timeReason: "잠들지 못한 사람들이 조용히 같은 방에 있는 것 같은 2시.",
  },
  {
    id: 303,
    nickname: "noa",
    youtubeUrl: "https://www.youtube.com/watch?v=DWcJFNfaw9c",
    comment: "해 뜨기 전 산책하다가 듣기 좋아요. 아직 아무 일도 시작되지 않은 차가운 공기가 같이 떠올라요.",
    thumbnailUrl: "https://i.ytimg.com/vi/DWcJFNfaw9c/hqdefault.jpg",
    title: "Morning Light",
    votes: 18,
    voters: [],
    createdAt: "2026-04-02T05:40:00.000Z",
    timeSlot: 5,
    timeReason: "도시가 아직 말수가 적고 빛만 천천히 늘어나는 시간.",
  },
  {
    id: 304,
    nickname: "rue",
    youtubeUrl: "https://www.youtube.com/watch?v=lTRiuFIWV54",
    comment: "출근길에 발걸음은 바쁜데 마음만큼은 한 칸 낮춰주는 곡이에요. 아침을 덜 급하게 시작하게 해줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/lTRiuFIWV54/hqdefault.jpg",
    title: "Sunrise Drive",
    votes: 7,
    voters: [],
    createdAt: "2026-04-03T07:25:00.000Z",
    timeSlot: 7,
    timeReason: "어제의 잔상이 남아 있지만 오늘의 리듬이 시작되는 7시.",
  },
  {
    id: 305,
    nickname: "sol",
    youtubeUrl: "https://www.youtube.com/watch?v=mPZkdNFkNps",
    comment: "첫 커피를 책상에 내려놓고 들으면 이제 정말 시작해도 되겠다는 느낌이 들어요. 집중 버튼 같은 곡이에요.",
    thumbnailUrl: "https://i.ytimg.com/vi/mPZkdNFkNps/hqdefault.jpg",
    title: "First Cup",
    votes: 22,
    voters: [],
    createdAt: "2026-04-03T09:05:00.000Z",
    timeSlot: 9,
    timeReason: "할 일이 선명해지고 책상 위 사물들이 제자리를 찾는 시간.",
  },
  {
    id: 306,
    nickname: "yoon",
    youtubeUrl: "https://www.youtube.com/watch?v=V1bFr2SWP1I",
    comment: "오전 일이 몰려올 때 들어도 너무 들뜨지 않아서 좋아요. 복잡한 머릿속을 부드럽게 정리해줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/V1bFr2SWP1I/hqdefault.jpg",
    title: "Soft Focus",
    votes: 11,
    voters: [],
    createdAt: "2026-04-04T10:15:00.000Z",
    timeSlot: 10,
    timeReason: "집중이 깊어지기 직전, 머릿속 잡음이 정리되는 10시.",
  },
  {
    id: 307,
    nickname: "ari",
    youtubeUrl: "https://www.youtube.com/watch?v=Dx5qFachd3A",
    comment: "점심 전 애매하게 남은 시간을 기분 좋게 밀어주는 곡이에요. 몸은 배고픈데 마음은 꽤 가벼워져요.",
    thumbnailUrl: "https://i.ytimg.com/vi/Dx5qFachd3A/hqdefault.jpg",
    title: "Golden Errands",
    votes: 6,
    voters: [],
    createdAt: "2026-04-04T11:50:00.000Z",
    timeSlot: 11,
    timeReason: "배가 조금 고프고 햇빛은 책상 끝까지 올라오는 시간.",
  },
  {
    id: 308,
    nickname: "dawn",
    youtubeUrl: "https://www.youtube.com/watch?v=kgx4WGK0oNU",
    comment: "점심 먹고 늘어지는 시간에 들으면 다시 의자에 제대로 앉게 돼요. 느슨한 공기를 천천히 정돈해줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/kgx4WGK0oNU/hqdefault.jpg",
    title: "After Lunch",
    votes: 12,
    voters: [],
    createdAt: "2026-04-05T13:20:00.000Z",
    timeSlot: 13,
    timeReason: "몸은 조금 느려지고 마음은 다시 방향을 잡아야 하는 1시.",
  },
  {
    id: 309,
    nickname: "june",
    youtubeUrl: "https://www.youtube.com/watch?v=AzV77KFsLn4",
    comment: "오후 집중력이 흐려질 때 틀면 조금 더 버틸 수 있어요. 일을 밀어붙이기보다 오래 붙잡아주는 느낌이에요.",
    thumbnailUrl: "https://i.ytimg.com/vi/AzV77KFsLn4/hqdefault.jpg",
    title: "Deep Work Window",
    votes: 20,
    voters: [],
    createdAt: "2026-04-05T15:10:00.000Z",
    timeSlot: 15,
    timeReason: "하루 중 가장 많은 것을 밀어낼 수 있는 조용한 중력의 시간.",
  },
  {
    id: 310,
    nickname: "lin",
    youtubeUrl: "https://www.youtube.com/watch?v=7NOSDKb0HlU",
    comment: "퇴근 직전 남은 일을 마무리할 때 들으면 좋아요. 이미 지친 하루에도 작은 광택이 생기는 기분이에요.",
    thumbnailUrl: "https://i.ytimg.com/vi/7NOSDKb0HlU/hqdefault.jpg",
    title: "Late Afternoon Gloss",
    votes: 8,
    voters: [],
    createdAt: "2026-04-06T17:45:00.000Z",
    timeSlot: 17,
    timeReason: "창밖 색이 낮에서 저녁으로 기울고 마감이 가까워지는 시간.",
  },
  {
    id: 311,
    nickname: "eden",
    youtubeUrl: "https://www.youtube.com/watch?v=Na0w3Mz46GA",
    comment: "저녁 먹고 방 안 조명을 낮출 때 잘 어울려요. 바깥의 속도에서 빠져나와 내 호흡으로 돌아오게 해줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/Na0w3Mz46GA/hqdefault.jpg",
    title: "Dim Room",
    votes: 16,
    voters: [],
    createdAt: "2026-04-06T20:05:00.000Z",
    timeSlot: 20,
    timeReason: "외부의 속도에서 빠져나와 나만의 온도로 돌아오는 8시.",
  },
  {
    id: 312,
    nickname: "sian",
    youtubeUrl: "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
    comment: "밤 작업할 때 에너지는 필요한데 너무 들뜨고 싶지는 않을 때 들어요. 차분하게 손을 움직이게 해줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZbZSe6N_BXs/hqdefault.jpg",
    title: "Midnight Draft",
    votes: 13,
    voters: [],
    createdAt: "2026-04-07T22:15:00.000Z",
    timeSlot: 22,
    timeReason: "피곤함과 몰입이 묘하게 균형을 이루는 늦은 밤.",
  },
  {
    id: 313,
    nickname: "vivi",
    youtubeUrl: "https://www.youtube.com/watch?v=WcIcVapfqXw",
    comment: "같은 밤이어도 이 곡을 들으면 소리가 조금 더 선명하게 느껴져요. 조용한 방 안에서 오래 남는 곡이에요.",
    thumbnailUrl: "https://i.ytimg.com/vi/WcIcVapfqXw/hqdefault.jpg",
    title: "Quiet Signal",
    votes: 5,
    voters: [],
    createdAt: "2026-04-08T22:35:00.000Z",
    timeSlot: 22,
    timeReason: "대화는 줄고 작은 소리들이 크게 느껴지는 10시대.",
  },
  {
    id: 314,
    nickname: "gray",
    youtubeUrl: "https://www.youtube.com/watch?v=kXYiU_JCYtU",
    comment: "잠들기 전 그냥 조용한 곡보다 마음을 한 번 흔들고 싶을 때 들어요. 듣고 나면 천천히 가라앉아요.",
    thumbnailUrl: "https://i.ytimg.com/vi/kXYiU_JCYtU/hqdefault.jpg",
    title: "Before Sleep",
    votes: 10,
    voters: [],
    createdAt: "2026-04-08T23:30:00.000Z",
    timeSlot: 23,
    timeReason: "오늘을 완전히 닫기 전, 마지막으로 감정이 또렷해지는 시간.",
  },
  {
    id: 315,
    nickname: "kio",
    youtubeUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
    comment: "헤드폰 안쪽에서만 작게 반짝이는 새벽 같은 곡이에요. 밖은 조용한데 혼자만 선명해지는 느낌이 있어요.",
    thumbnailUrl: "https://i.ytimg.com/vi/3JZ_D3ELwOQ/hqdefault.jpg",
    title: "Chrome Echo",
    votes: 17,
    voters: [],
    createdAt: "2026-04-09T00:47:00.000Z",
    timeSlot: 0,
    timeMinute: 47,
    timeReason: "자정이 조금 지나고 방의 윤곽만 남는 시간.",
  },
  {
    id: 316,
    nickname: "mae",
    youtubeUrl: "https://www.youtube.com/watch?v=fLexgOxsZu0",
    comment: "아무도 깨우지 않고 내 기분만 살짝 올리고 싶을 때 들어요. 새벽의 조심스러운 텐션이 마음에 들어요.",
    thumbnailUrl: "https://i.ytimg.com/vi/fLexgOxsZu0/hqdefault.jpg",
    title: "Tiny Upstairs",
    votes: 4,
    voters: [],
    createdAt: "2026-04-09T01:12:00.000Z",
    timeSlot: 1,
    timeMinute: 12,
    timeReason: "생각이 옆방처럼 가까이 들리는 새벽 1시.",
  },
  {
    id: 317,
    nickname: "oz",
    youtubeUrl: "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    comment: "어둠이 완전히 무거워지기 전에 남아 있는 탄력이 느껴져요. 잠들긴 아쉽고 더 움직이고 싶은 밤에 좋아요.",
    thumbnailUrl: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
    title: "Afterimage Pop",
    votes: 15,
    voters: [],
    createdAt: "2026-04-09T02:38:00.000Z",
    timeSlot: 2,
    timeMinute: 38,
    timeReason: "잠과 몰입 사이에서 리듬이 또렷해지는 시간.",
  },
  {
    id: 318,
    nickname: "min",
    youtubeUrl: "https://www.youtube.com/watch?v=09R8_2nJtjg",
    comment: "새벽 공기 위에 베이스가 얇게 올라가는 느낌이에요. 집으로 돌아가는 길에 들으면 발끝이 가벼워져요.",
    thumbnailUrl: "https://i.ytimg.com/vi/09R8_2nJtjg/hqdefault.jpg",
    title: "Blue Walk Home",
    votes: 19,
    voters: [],
    createdAt: "2026-04-09T05:52:00.000Z",
    timeSlot: 5,
    timeMinute: 52,
    timeReason: "해가 뜨기 직전, 색이 아직 결정되지 않은 시간.",
  },
  {
    id: 319,
    nickname: "chae",
    youtubeUrl: "https://www.youtube.com/watch?v=RgKAFK5djSk",
    comment: "커튼 사이로 첫 파란빛이 들어올 때 들으면 좋아요. 아직 하루가 말 걸기 전의 조용한 아침 같아요.",
    thumbnailUrl: "https://i.ytimg.com/vi/RgKAFK5djSk/hqdefault.jpg",
    title: "Curtain Blue",
    votes: 21,
    voters: [],
    createdAt: "2026-04-10T06:08:00.000Z",
    timeSlot: 6,
    timeMinute: 8,
    timeReason: "아침이 아직 조용하고 하늘만 먼저 밝아지는 시간.",
  },
  {
    id: 320,
    nickname: "ji",
    youtubeUrl: "https://www.youtube.com/watch?v=60ItHLz5WEA",
    comment: "등교길과 출근길 사이 어딘가의 가벼운 텐션이 있어요. 사람들 사이를 지나가도 기분이 덜 복잡해져요.",
    thumbnailUrl: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
    title: "Bus Stop Crush",
    votes: 13,
    voters: [],
    createdAt: "2026-04-10T07:11:00.000Z",
    timeSlot: 7,
    timeMinute: 11,
    timeReason: "하루가 밖으로 나가기 시작하는 7시 초반.",
  },
  {
    id: 321,
    nickname: "reva",
    youtubeUrl: "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    comment: "집중하려고 앉았는데 먼저 어깨가 움직이는 곡이에요. 그래도 이상하게 일 시작하기가 더 쉬워져요.",
    thumbnailUrl: "https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg",
    title: "Desk Groove",
    votes: 24,
    voters: [],
    createdAt: "2026-04-10T09:18:00.000Z",
    timeSlot: 9,
    timeMinute: 18,
    timeReason: "일이 시작되지만 마음은 아직 음악을 믿고 싶은 시간.",
  },
  {
    id: 322,
    nickname: "toma",
    youtubeUrl: "https://www.youtube.com/watch?v=34Na4j8AVgA",
    comment: "9시대의 다른 속도를 남기고 싶어서 골랐어요. 비슷한 아침이어도 몇 분 차이로 기분이 달라지더라고요.",
    thumbnailUrl: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
    title: "Nine Twenty Two",
    votes: 8,
    voters: [],
    createdAt: "2026-04-10T09:22:00.000Z",
    timeSlot: 9,
    timeMinute: 22,
    timeReason: "몇 분 차이로 기분이 다른 아침 업무의 틈.",
  },
  {
    id: 323,
    nickname: "nari",
    youtubeUrl: "https://www.youtube.com/watch?v=UceaB4D0jpo",
    comment: "오전이 거의 낮으로 넘어갈 때의 선명함이 있어요. 햇빛이 책상 위를 완전히 차지하기 직전에 어울려요.",
    thumbnailUrl: "https://i.ytimg.com/vi/UceaB4D0jpo/hqdefault.jpg",
    title: "Almost Noon",
    votes: 12,
    voters: [],
    createdAt: "2026-04-11T11:04:00.000Z",
    timeSlot: 11,
    timeMinute: 4,
    timeReason: "햇빛이 책상 위를 완전히 차지하기 직전.",
  },
  {
    id: 324,
    nickname: "loen",
    youtubeUrl: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y",
    comment: "점심 먹고 다시 리듬을 찾아야 할 때 첫 곡으로 좋아요. 늘어진 몸을 화면 앞으로 데려와줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/Zi_XLOBDo_Y/hqdefault.jpg",
    title: "Lunch Reset",
    votes: 10,
    voters: [],
    createdAt: "2026-04-11T12:42:00.000Z",
    timeSlot: 12,
    timeMinute: 42,
    timeReason: "느슨해진 몸을 다시 화면 앞으로 데려오는 시간.",
  },
  {
    id: 325,
    nickname: "bora",
    youtubeUrl: "https://www.youtube.com/watch?v=YQHsXMglC9A",
    comment: "오후 3시에 잠깐 다른 장면으로 넘어가는 느낌이에요. 작은 영화 예고편처럼 기분을 환기해줘요.",
    thumbnailUrl: "https://i.ytimg.com/vi/YQHsXMglC9A/hqdefault.jpg",
    title: "Third Floor Cinema",
    votes: 18,
    voters: [],
    createdAt: "2026-04-11T15:48:00.000Z",
    timeSlot: 15,
    timeMinute: 48,
    timeReason: "오후가 길어지고 마음이 다른 장면을 찾는 시간.",
  },
  {
    id: 326,
    nickname: "ikai",
    youtubeUrl: "https://www.youtube.com/watch?v=YqeW9_5kURI",
    comment: "퇴근 직전의 공기를 조금 반짝이게 만들어줘요. 아직 할 일은 남았지만 마음이 먼저 가벼워지는 곡이에요.",
    thumbnailUrl: "https://i.ytimg.com/vi/YqeW9_5kURI/hqdefault.jpg",
    title: "Pre Sunset Loop",
    votes: 16,
    voters: [],
    createdAt: "2026-04-12T17:55:00.000Z",
    timeSlot: 17,
    timeMinute: 55,
    timeReason: "낮이 끝났다고 말하기엔 아직 빛이 남은 시간.",
  },
  {
    id: 327,
    nickname: "sue",
    youtubeUrl: "https://www.youtube.com/watch?v=hT_nvWreIhg",
    comment: "해가 내려가는 순간에 들으면 괜히 하루가 드라마처럼 느껴져요. 별일 없던 날도 장면이 생겨요.",
    thumbnailUrl: "https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg",
    title: "Coral Hour",
    votes: 27,
    voters: [],
    createdAt: "2026-04-12T18:13:00.000Z",
    timeSlot: 18,
    timeMinute: 13,
    timeReason: "건물 유리창이 잠깐 다른 색으로 바뀌는 시간.",
  },
  {
    id: 328,
    nickname: "rani",
    youtubeUrl: "https://www.youtube.com/watch?v=uelHwf8o7_U",
    comment: "18시 곡 바로 옆에 붙여두고 싶은 조금 더 진한 저녁이에요. 몇 분 사이에 빛의 온도가 달라져요.",
    thumbnailUrl: "https://i.ytimg.com/vi/uelHwf8o7_U/hqdefault.jpg",
    title: "Six Twenty Glow",
    votes: 9,
    voters: [],
    createdAt: "2026-04-12T18:21:00.000Z",
    timeSlot: 18,
    timeMinute: 21,
    timeReason: "몇 분 사이에 노을의 온도가 달라지는 시간.",
  },
  {
    id: 329,
    nickname: "moss",
    youtubeUrl: "https://www.youtube.com/watch?v=RBumgq5yVrA",
    comment: "밤이 됐지만 아직 집에 들어가긴 아쉬울 때 어울려요. 간판 불빛과 사람 소리가 리듬처럼 들려요.",
    thumbnailUrl: "https://i.ytimg.com/vi/RBumgq5yVrA/hqdefault.jpg",
    title: "Night Market Tape",
    votes: 14,
    voters: [],
    createdAt: "2026-04-12T21:06:00.000Z",
    timeSlot: 21,
    timeMinute: 6,
    timeReason: "간판과 사람 소리가 낮 대신 리듬이 되는 시간.",
  },
  {
    id: 330,
    nickname: "uno",
    youtubeUrl: "https://www.youtube.com/watch?v=ktvTqknDobU",
    comment: "23시 50분쯤 들으면 하루의 엔딩 크레딧 같아요. 끝났지만 한 곡만 더 듣고 싶은 마음이 남아요.",
    thumbnailUrl: "https://i.ytimg.com/vi/ktvTqknDobU/hqdefault.jpg",
    title: "Last Train Credits",
    votes: 20,
    voters: [],
    createdAt: "2026-04-12T23:50:00.000Z",
    timeSlot: 23,
    timeMinute: 50,
    timeReason: "끝났지만 아직 한 곡 더 듣고 싶은 거의 자정.",
  },
];
