/* This file is generated by scripts/generate-season-songs.mjs. Do not edit manually. */

export type Season = 1 | 2 | 3;

export type Song = {
  id: string;
  season: Season;
  nickname: string;
  title: string;
  artist?: string;
  comment: string;
  youtubeUrl: string;
  thumbnailUrl?: string;
  votes: number;
  createdAt?: string;
  time?: string;
  trackOrder: number;
  voters: string[];
};

export const songsBySeason: Record<Season, Song[]> = {
  "1": [
    {
      "id": "s1-2",
      "season": 1,
      "nickname": "수리",
      "title": "Superfantastic",
      "comment": "한화이글스 심우준 선수의 응원가이기도 한 노래입니다아 듣기만 해도 힘이나는 노래입니당🎶",
      "youtubeUrl": "https://www.youtube.com/watch?v=S9MSmTEm3sQ&list=RDS9MSmTEm3sQ&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/S9MSmTEm3sQ/hqdefault.jpg",
      "votes": 5,
      "createdAt": "2026-03-17 04:32:29.718156+00",
      "trackOrder": 1,
      "voters": [
        "링쿠",
        "맥스",
        "다니",
        "프리송",
        "스페로"
      ]
    },
    {
      "id": "s1-10",
      "season": 1,
      "nickname": "비비",
      "title": "g0nny (거니) Feat. SHIRT - 같애 [가사]",
      "comment": "도입부 들어가는 가수 거니의 음색이 너무 좋고 들으면 기분이 좋아짐! 🥸🎶",
      "youtubeUrl": "https://youtu.be/_2sLU4RfWOY?si=76p_CA0EwxZoBtgC",
      "thumbnailUrl": "https://img.youtube.com/vi/_2sLU4RfWOY/hqdefault.jpg",
      "votes": 5,
      "createdAt": "2026-03-17 11:39:20.837465+00",
      "trackOrder": 2,
      "voters": [
        "프리송",
        "링쿠",
        "수리",
        "스우",
        "로렌"
      ]
    },
    {
      "id": "s1-3",
      "season": 1,
      "nickname": "다니",
      "title": "Alec Benjamin - Water Fountain [Official Lyric Video]",
      "comment": "요즘은 유튜브 플리를 많이 들어서 그냥 추천하고 싶은 음악 제 플리에서 가져와 봤어요!",
      "youtubeUrl": "https://youtu.be/6uFWshoWTLU?si=zDjdQx_k0VwvnesD",
      "thumbnailUrl": "https://img.youtube.com/vi/6uFWshoWTLU/hqdefault.jpg",
      "votes": 4,
      "createdAt": "2026-03-17 05:28:07.580105+00",
      "trackOrder": 3,
      "voters": [
        "링쿠",
        "샨",
        "프리송",
        "수리"
      ]
    },
    {
      "id": "s1-7",
      "season": 1,
      "nickname": "Craig",
      "title": "나토리 - overdose [가사/독음]",
      "comment": "이 감성, 그 자체가 Frisson.",
      "youtubeUrl": "https://www.youtube.com/watch?v=OKoydpFRd1U",
      "thumbnailUrl": "https://img.youtube.com/vi/OKoydpFRd1U/hqdefault.jpg",
      "votes": 4,
      "createdAt": "2026-03-17 11:33:01.126699+00",
      "trackOrder": 4,
      "voters": [
        "프리송",
        "링쿠",
        "수리",
        "메이슨"
      ]
    },
    {
      "id": "s1-11",
      "season": 1,
      "nickname": "빈",
      "title": "이승철 - 아마추어 [Lyrics/가사]",
      "comment": "\"아무도 가르쳐 주지 않기에, 모두가 처음 서 보기 때문에...\"",
      "youtubeUrl": "https://www.youtube.com/watch?v=t_fQQ8tvpz0&list=RDt_fQQ8tvpz0&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/t_fQQ8tvpz0/hqdefault.jpg",
      "votes": 4,
      "createdAt": "2026-03-17 11:53:51.644839+00",
      "trackOrder": 5,
      "voters": [
        "s",
        "프리송",
        ".",
        "곤잘레스"
      ]
    },
    {
      "id": "s1-15",
      "season": 1,
      "nickname": "헤더",
      "title": "twenty one pilots - City Walls (Official Audio)",
      "comment": "이 곡으로 말할 것 같으면 작년 추석 시골로 내려가는 KTX 기차를 탄 날로 거슬러 올라갑니다... 수많은 칸쵸 중에서 제 이름을 찾아 기뻐하다가 옆사람에게 칸쵸 하나 드실래요 하고 말을 걸었습니다 옆자리 사람은 한국 여행을 하던 스페인 사람이었어요.. 제가 밴드 음악을 좋아한다고 하니 고민없이 추천해 준 아티스트입니다. 그 때 이후로 이 노래를 들으면 그 때로 돌아간 것 같아요. 추억보정이 된 거 아니냐고 하실 수 있지만 객관적으로 좋은 노래입니다. 마지막까지 울부짖는 흐름도 좋고 중간중간 신기한 소리가 들리는데 한 번 들어보시기를 권합니다. 저는 보통 아르바이트 끝나고 집가는 만원 지하철에서 한 곡 재생으로 들었어요. 지옥같은 시간들을 버틸 수 있게 해준 소중한 노래입니다. 지금도 들으면서 심장이 막 뛰네요.. 이만 줄이겠습니다.",
      "youtubeUrl": "https://www.youtube.com/watch?v=EjZ1qxbH2nk",
      "thumbnailUrl": "https://img.youtube.com/vi/EjZ1qxbH2nk/hqdefault.jpg",
      "votes": 4,
      "createdAt": "2026-03-17 12:30:04.042339+00",
      "trackOrder": 6,
      "voters": [
        "프리송",
        "피비",
        "나나",
        "로렌"
      ]
    },
    {
      "id": "s1-20",
      "season": 1,
      "nickname": "이브",
      "title": "BUMP OF CHICKEN「天体観測」",
      "comment": "미래만을 걱정하기엔 너무나 아까운 '오늘, 지금 이 순간'을 위한 곡",
      "youtubeUrl": "https://youtu.be/j7CDb610Bg0?si=xAbzEdDsWQpLpWTy",
      "thumbnailUrl": "https://img.youtube.com/vi/j7CDb610Bg0/hqdefault.jpg",
      "votes": 4,
      "createdAt": "2026-03-18 02:39:52.450244+00",
      "trackOrder": 7,
      "voters": [
        "링쿠",
        "Craig",
        "수리",
        "프리송"
      ]
    },
    {
      "id": "s1-1",
      "season": 1,
      "nickname": "링쿠",
      "title": "Higher",
      "comment": "천상의 목소리란 이런 것...? 😇 👼 ",
      "youtubeUrl": "https://www.youtube.com/watch?v=XQ0WuIggk8U&pp=ygUPZCdhbmdlbG8gaGlnaGVy",
      "thumbnailUrl": "https://img.youtube.com/vi/XQ0WuIggk8U/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-17 04:15:43.180459+00",
      "trackOrder": 8,
      "voters": [
        "프리송",
        "맥스",
        "수리"
      ]
    },
    {
      "id": "s1-9",
      "season": 1,
      "nickname": "프리송",
      "title": "Swingin' Spathiphyllums",
      "comment": "이거 진짜 아끼는 앨범인데... 식물의 세계로 초대합니다!",
      "youtubeUrl": "https://youtu.be/C1yzxgNLChI?si=dn0LMk0LFSeyMDBN",
      "thumbnailUrl": "https://img.youtube.com/vi/C1yzxgNLChI/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-17 11:38:45.888216+00",
      "trackOrder": 9,
      "voters": [
        "링쿠",
        "이브",
        "수리"
      ]
    },
    {
      "id": "s1-13",
      "season": 1,
      "nickname": "Tom(톰)",
      "title": "[Official Audio] 카더가든 (Car, the garden) - 그대 작은 나의 세상이 되어",
      "comment": "노래 가사가 서정적이고, 멜로디가 좋아서요",
      "youtubeUrl": "https://youtu.be/ZurHW2kBqrw?si=cGQb2vYm6V5RHryd",
      "thumbnailUrl": "https://img.youtube.com/vi/ZurHW2kBqrw/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-17 12:07:07.391026+00",
      "trackOrder": 10,
      "voters": [
        "프리송",
        ".",
        "메이슨"
      ]
    },
    {
      "id": "s1-16",
      "season": 1,
      "nickname": "넵튠",
      "title": "윤하(YOUNHA) - 태양물고기 M/V",
      "comment": "윤하의 태양물고기는 개복치에 관한 노래랍니다. 괴로울 때 많은 위로를 받았던 곡이에요. \"어떤 누구의 얘기도 기꺼이 미소 짓도록 단단한 내가 되기를\"🐟",
      "youtubeUrl": "https://www.youtube.com/watch?v=ehX7MAhc5iA",
      "thumbnailUrl": "https://img.youtube.com/vi/ehX7MAhc5iA/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-17 13:01:38.91074+00",
      "trackOrder": 11,
      "voters": [
        "프리송",
        "수리",
        "링쿠"
      ]
    },
    {
      "id": "s1-19",
      "season": 1,
      "nickname": "시우",
      "title": "Novelbright - ツキミソウ [Official Music Video]",
      "comment": "처음 듣자마자 가사를 몰라도 멜로디가 너무 좋아서 감동받았던 노래입니다. ",
      "youtubeUrl": "https://www.youtube.com/watch?v=WAMxwRtNrPY",
      "thumbnailUrl": "https://img.youtube.com/vi/WAMxwRtNrPY/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-17 15:05:50.000136+00",
      "trackOrder": 12,
      "voters": [
        "ㅡ",
        "링쿠",
        "수리"
      ]
    },
    {
      "id": "s1-21",
      "season": 1,
      "nickname": "네이선",
      "title": "사랑하지 않으니까요",
      "comment": "첫 건반 화음이 깊이 빠져들게 만들어요!",
      "youtubeUrl": "https://youtu.be/NYrZRVKIk6E?si=ivnyWQRSb4ZG0Y-h",
      "thumbnailUrl": "https://img.youtube.com/vi/NYrZRVKIk6E/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-18 04:55:34.016303+00",
      "trackOrder": 13,
      "voters": [
        "프리송",
        "링쿠",
        "수리"
      ]
    },
    {
      "id": "s1-49",
      "season": 1,
      "nickname": "키위",
      "title": "백예린 (Yerin Baek) - '물고기' Music Video",
      "comment": "노래에서 여름 밤 냄새가 나요🫠🫧",
      "youtubeUrl": "https://youtu.be/DNf6mIZz6Zo?si=xeyX55ksHjHB3GlI",
      "thumbnailUrl": "https://img.youtube.com/vi/DNf6mIZz6Zo/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-03-26 01:59:12.521233+00",
      "trackOrder": 14,
      "voters": [
        "프리송",
        "링쿠",
        "메이슨"
      ]
    },
    {
      "id": "s1-14",
      "season": 1,
      "nickname": "테이",
      "title": "권진아 'Silly Silly Love' Live Clip | Kwon Jin Ah 'Silly Silly Love'",
      "comment": "안개 속에 있는 듯한 목소리와 푸르고 살랑이는 이 영상의 분위기가 정말 좋아요",
      "youtubeUrl": "https://www.youtube.com/watch?v=Zx4zjLjOlFU&list=RDZx4zjLjOlFU&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/Zx4zjLjOlFU/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-03-17 12:25:15.198109+00",
      "trackOrder": 15,
      "voters": [
        "프리송",
        "주키"
      ]
    },
    {
      "id": "s1-24",
      "season": 1,
      "nickname": "스페로",
      "title": "[MV] Zion.T(자이언티) _ No Make Up(노메이크업)",
      "comment": "아무리 얘기해도 넌 모르겠다고 하지만 \n오늘 내일 다음 날도 매일 말해 주고파\n넌 그냥 그대로 너무 예쁜 걸",
      "youtubeUrl": "https://youtu.be/eqcte1r3aiQ?si=RRSYeDOqKVA5WK6n",
      "thumbnailUrl": "https://img.youtube.com/vi/eqcte1r3aiQ/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-03-21 05:13:42.785233+00",
      "trackOrder": 16,
      "voters": [
        "링쿠",
        "."
      ]
    },
    {
      "id": "s1-32",
      "season": 1,
      "nickname": "도니",
      "title": "FKJ & Masego - Tadow",
      "comment": "yeah",
      "youtubeUrl": "https://www.youtube.com/watch?v=hC8CH0Z3L54",
      "thumbnailUrl": "https://img.youtube.com/vi/hC8CH0Z3L54/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-03-24 11:50:26.047584+00",
      "trackOrder": 17,
      "voters": [
        "아롬",
        "프리송"
      ]
    },
    {
      "id": "s1-38",
      "season": 1,
      "nickname": "BK",
      "title": "La nostra storia",
      "comment": "이탈리아 뽕맛",
      "youtubeUrl": "https://www.youtube.com/watch?v=EjKR7zIIaO0",
      "thumbnailUrl": "https://img.youtube.com/vi/EjKR7zIIaO0/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-03-25 08:35:37.003791+00",
      "trackOrder": 18,
      "voters": [
        "아롬",
        "Rudy"
      ]
    },
    {
      "id": "s1-48",
      "season": 1,
      "nickname": "실라",
      "title": "AURORA - Daydreamer",
      "comment": "WWDC20 오프닝 곡 AURORA의 Daydreamer입니다!\n우리 모두 몽상가가 되.. 💭",
      "youtubeUrl": "https://youtu.be/9KAQaKydqA0?si=_V_Kaqn7dMRSZbqq",
      "thumbnailUrl": "https://img.youtube.com/vi/9KAQaKydqA0/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-03-25 23:14:41.019193+00",
      "trackOrder": 19,
      "voters": [
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s1-50",
      "season": 1,
      "nickname": "사야",
      "title": "[MV] 아웃오브블루 (Out of Blue) - 사랑이 없다면 (IF NO LOVE) / Official Music Video",
      "comment": "세상의 모든것은 마음 + 사랑!",
      "youtubeUrl": "https://www.youtube.com/watch?v=WliLXAyqpKs",
      "thumbnailUrl": "https://img.youtube.com/vi/WliLXAyqpKs/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-03-27 00:15:30.271743+00",
      "trackOrder": 20,
      "voters": [
        "링쿠",
        "프리송"
      ]
    },
    {
      "id": "s1-4",
      "season": 1,
      "nickname": "별일없이산다",
      "title": "장기하 - 별일 없이 산다 [더 시즌즈-이영지의 레인보우] | KBS 240927 방송",
      "comment": "나의 신나는 하교를 책임져주던 음악",
      "youtubeUrl": "https://youtu.be/CMnCQS2AW6s?si=_ogb_omcYtiBdEp6",
      "thumbnailUrl": "https://img.youtube.com/vi/CMnCQS2AW6s/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 11:27:58.137288+00",
      "trackOrder": 21,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-5",
      "season": 1,
      "nickname": "도넛!",
      "title": "Wednesday Girl",
      "comment": "노래는 더운 분위기인데 가사가 귀여워요!",
      "youtubeUrl": "https://youtu.be/yMqekPtvjmI?si=gpdaYAb0qkLPg_Aq",
      "thumbnailUrl": "https://img.youtube.com/vi/yMqekPtvjmI/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 11:28:02.991333+00",
      "trackOrder": 22,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-6",
      "season": 1,
      "nickname": "주키",
      "title": "怪獣の花唄　歌ってみたのはメガテラ・ゼロ",
      "comment": "괴수의 꽃노래.. 원곡은 바운디지만 메가테라제로라는 분의 음색이 좋아서 자주 듣습니다! \n점점 고조되는 노래와 메가테라제로의 목소리가 합쳐지니 답답했던 제 속이 뻥 뚫리더라고요! 작업할 때나 열받을 때 추천드립니다 ㅎㅎ",
      "youtubeUrl": "https://youtu.be/bc9lcY5nzQQ?si=e8UP2fJ61umicuu6",
      "thumbnailUrl": "https://img.youtube.com/vi/bc9lcY5nzQQ/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 11:28:03.014405+00",
      "trackOrder": 23,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-8",
      "season": 1,
      "nickname": "샨",
      "title": "Sia - Original (from the Dolittle soundtrack) (Lyric Video)",
      "comment": "나만의 길을 걷고자 하는 우리들에게 어울리는 노래",
      "youtubeUrl": "https://www.youtube.com/watch?v=epvRvotlZg0",
      "thumbnailUrl": "https://img.youtube.com/vi/epvRvotlZg0/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 11:34:29.690846+00",
      "trackOrder": 24,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-12",
      "season": 1,
      "nickname": "나나",
      "title": "dreams, books, power and walls (꿈과 책과 힘과 벽)",
      "comment": "우리는 우리는 어째서 어른이 된 걸까...",
      "youtubeUrl": "https://youtu.be/SJUWooZnfVQ?si=0MTkhd-BarZ1J4zb",
      "thumbnailUrl": "https://img.youtube.com/vi/SJUWooZnfVQ/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 11:56:22.27487+00",
      "trackOrder": 25,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-17",
      "season": 1,
      "nickname": "피비",
      "title": "WOODZ 'To My January' Live Clip (2025 WOODZ PREVIEW CONCERT : index_00)",
      "comment": "지구가 멸망하지 않는 한 모두에게 1월은 꼭 올 거다!라는 메세지를 담은 노래에요. 목표를 이뤄가는 과정에서 까지더라도 흉 지지는 않기를 바라며・・・",
      "youtubeUrl": "https://www.youtube.com/watch?v=VRd67JrpIvg",
      "thumbnailUrl": "https://img.youtube.com/vi/VRd67JrpIvg/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 13:43:18.505799+00",
      "trackOrder": 26,
      "voters": [
        "주키"
      ]
    },
    {
      "id": "s1-18",
      "season": 1,
      "nickname": "하르딘",
      "title": "[MV] 구원찬(Kuonechan) - 슬퍼하지마(Don't Be Sad) / Official Music Video",
      "comment": "나는 너에게 다 괜찮다고 말하고 싶어! 저의 고등학교 시절이 담긴 노래입니당.",
      "youtubeUrl": "https://youtu.be/BWRVkHg8Rjs?si=fVDJR7F9ZJ50K_1t",
      "thumbnailUrl": "https://img.youtube.com/vi/BWRVkHg8Rjs/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-17 14:46:07.733698+00",
      "trackOrder": 27,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-22",
      "season": 1,
      "nickname": "캇",
      "title": "Tamashiinoibasyo",
      "comment": "저의 19살을 책임졌던 인생 jpop입니다…정말루 들으면 머리가 맑아지는 느낌이랄까",
      "youtubeUrl": "https://youtu.be/C5omeyknLdI?si=7L_PyNWje5rq6r94",
      "thumbnailUrl": "https://img.youtube.com/vi/C5omeyknLdI/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-18 06:47:59.409379+00",
      "trackOrder": 28,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-23",
      "season": 1,
      "nickname": "메이슨",
      "title": "Nothing But Thieves - Impossible (Orchestral Version - Live at Abbey Road)",
      "comment": "이렇게나 그대에게 가라앉게 될 줄 몰랐어요",
      "youtubeUrl": "https://www.youtube.com/watch?v=8irM5QFkr6Q",
      "thumbnailUrl": "https://img.youtube.com/vi/8irM5QFkr6Q/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-19 13:56:46.602858+00",
      "trackOrder": 29,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-25",
      "season": 1,
      "nickname": "스우",
      "title": "Sweet Sue, Just You",
      "comment": "저는 Sue, 나를 위한 재즈 곡이 있다니 온 몸이 짜릿하지 않나요?",
      "youtubeUrl": "https://youtu.be/GXsK7KjAfs0?si=oaoMj2Rw5Tiqv8dI",
      "thumbnailUrl": "https://img.youtube.com/vi/GXsK7KjAfs0/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-21 12:59:04.685715+00",
      "trackOrder": 30,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-27",
      "season": 1,
      "nickname": "쿄조",
      "title": "Sunday Girl",
      "comment": "몽환적이지만 리드하는 드럼비트와 모든 것이 아름다운 노래",
      "youtubeUrl": "https://www.youtube.com/watch?v=ieUJRLZg_UU",
      "thumbnailUrl": "https://img.youtube.com/vi/ieUJRLZg_UU/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-24 10:23:43.359919+00",
      "trackOrder": 31,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-28",
      "season": 1,
      "nickname": "코리",
      "title": "Kaytranada - You're The One (Ft. Syd)",
      "comment": "그냥.. 몸을 가만히둘수없어요..",
      "youtubeUrl": "https://www.youtube.com/watch?v=AC_7snhNoCk&list=RDAC_7snhNoCk&start_radio=1&pp=ygUNeW91cmUgdGhlIG9uZaAHAQ%3D%3D",
      "thumbnailUrl": "https://img.youtube.com/vi/AC_7snhNoCk/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-24 10:26:36.205863+00",
      "trackOrder": 32,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-29",
      "season": 1,
      "nickname": "마치",
      "title": "[온스테이지2.0] wave to earth - nouvelle vague",
      "comment": "nouvelle vague! 4년째 제 인생곡입니다… (꼭 온스테이지 버전으로 들으셔야합니다)",
      "youtubeUrl": "https://youtu.be/Ht4h6WxEbU0?si=_JNAkq4wDg4V7YtP",
      "thumbnailUrl": "https://img.youtube.com/vi/Ht4h6WxEbU0/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-24 10:39:38.913836+00",
      "trackOrder": 33,
      "voters": [
        "메이슨"
      ]
    },
    {
      "id": "s1-30",
      "season": 1,
      "nickname": "무구",
      "title": "[MV] 한로로 (HANRORO) - 하루살이 (Mayfly)",
      "comment": "다음 봄에는 우리 바다 위에서 태어나자",
      "youtubeUrl": "https://youtu.be/ss_WdwNGawM?si=ZSLfu--8QRlQ_44Q",
      "thumbnailUrl": "https://img.youtube.com/vi/ss_WdwNGawM/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-24 11:45:30.815222+00",
      "trackOrder": 34,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-31",
      "season": 1,
      "nickname": "제리",
      "title": "Daniel Caesar - Superpowers (Official Audio)",
      "comment": "다니엘 시저의 곡들 중 가장 먼저 떠오르네요!",
      "youtubeUrl": "https://www.youtube.com/watch?v=rScwLoES2bM&list=RDrScwLoES2bM&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/rScwLoES2bM/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-24 11:47:01.716499+00",
      "trackOrder": 35,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-33",
      "season": 1,
      "nickname": "로렌",
      "title": "I'MIN - Balloons",
      "comment": "한번 들으면 한동안 귀에 맴돌아요 많은 사람들이 들어줬으면..🩵",
      "youtubeUrl": "https://youtu.be/sRK_5SbRxao?si=jtG3RgpXpkpFPWGt",
      "thumbnailUrl": "https://img.youtube.com/vi/sRK_5SbRxao/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-24 13:18:26.847899+00",
      "trackOrder": 36,
      "voters": [
        "카를"
      ]
    },
    {
      "id": "s1-39",
      "season": 1,
      "nickname": "Rudy",
      "title": "HITCHHIKER",
      "comment": "도입부가 설레고 바다가 생각나요.",
      "youtubeUrl": "https://youtu.be/1rHU8mznhaw?si=u18rmSVzwD5l8M-q",
      "thumbnailUrl": "https://img.youtube.com/vi/1rHU8mznhaw/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 08:40:40.677452+00",
      "trackOrder": 37,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-40",
      "season": 1,
      "nickname": "지나",
      "title": "Fred again.. & Anderson .Paak - places to be (Eagle Rock, 16th April 2024) feat Chika",
      "comment": "유튜브 링크 보자마자 이 영상이 바로 떠올랐어요. 노래도 노래지만 영상이랑 같이 보는거 추천입니다 ~~",
      "youtubeUrl": "https://youtu.be/0bVFEOb39vk?si=bnnlMtbDsDdRKJ0f",
      "thumbnailUrl": "https://img.youtube.com/vi/0bVFEOb39vk/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 09:16:43.364685+00",
      "trackOrder": 38,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-41",
      "season": 1,
      "nickname": "또치",
      "title": "Red Hot Chili Peppers - Sick Love [Lyrics]",
      "comment": "고등학생 때부터 즐겨들은… 노래입니다\n들을게 없을 때마다 이 노래로 돌아와요",
      "youtubeUrl": "https://youtu.be/MWbV_oNdqI8?si=bwPglRwF7sO0wine",
      "thumbnailUrl": "https://img.youtube.com/vi/MWbV_oNdqI8/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 09:27:25.303352+00",
      "trackOrder": 39,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-43",
      "season": 1,
      "nickname": "루미",
      "title": "트랜스픽션 (TransFixion) - 내게 돌아와 (Music Video)",
      "comment": "명곡이다",
      "youtubeUrl": "https://youtu.be/Oupn-dzr0P4?si=ZRnmoSDz657eQw-i",
      "thumbnailUrl": "https://img.youtube.com/vi/Oupn-dzr0P4/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 09:32:51.005838+00",
      "trackOrder": 40,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-44",
      "season": 1,
      "nickname": "리오르",
      "title": "[MV] BUMKEY(범키) _ COVID-19(여기저기거기) (Feat. SUPERBEE(수퍼비))",
      "comment": "주말에 쉴때 들으면 좋아요",
      "youtubeUrl": "https://youtu.be/5zjWC2Kj5jQ?si=38YY7M3ySIoo0uTI",
      "thumbnailUrl": "https://img.youtube.com/vi/5zjWC2Kj5jQ/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 09:37:26.130736+00",
      "trackOrder": 41,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-45",
      "season": 1,
      "nickname": "아롬",
      "title": "Elis Regina & Tom Jobim -  \"Aguas de Março\" - 1974",
      "comment": "가사가 좋고, 가사를 말하는 방식이 좋아요. 3월이 가기 전에 3월의 비(Aguas de Março)를 들어보세요.",
      "youtubeUrl": "https://youtube.com/watch?v=E1tOV7y94DY&pp=ygUNYWd1YSBkZSBtYXJjbw%3D%3D",
      "thumbnailUrl": "https://img.youtube.com/vi/E1tOV7y94DY/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 10:36:44.393655+00",
      "trackOrder": 42,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-46",
      "season": 1,
      "nickname": "에스더",
      "title": "WOODZ 'CINEMA' Live Clip (2025 WOODZ PREVIEW CONCERT : index_00)",
      "comment": "요즘 이 곡만 들어요…",
      "youtubeUrl": "https://youtu.be/N_eqwatYCv0",
      "thumbnailUrl": "https://img.youtube.com/vi/N_eqwatYCv0/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 14:03:46.050746+00",
      "trackOrder": 43,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-47",
      "season": 1,
      "nickname": "신디",
      "title": "[온스테이지 ] 페퍼톤스_행운을 빌어요",
      "comment": "아카데미 첫날에도 들은 곡 긴장되는 날엔 행운을 빌어주는 이 노래를 꼭 듣는 것 같아요~ 아침에 들으면 정말 기분이 좋아진답니당",
      "youtubeUrl": "https://www.youtube.com/watch?v=Tqlarp99Ovs",
      "thumbnailUrl": "https://img.youtube.com/vi/Tqlarp99Ovs/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-25 16:16:34.093976+00",
      "trackOrder": 44,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-51",
      "season": 1,
      "nickname": "케이",
      "title": "나는 문제없어 (노홍철)",
      "comment": "여기, 이곳 포항에서 어떤 행동을 하든 이 노래를 한번더 곱씹어 들으면서 나에게 다짐을 하지요.\n특히 노홍철버전이 제일 좋지요.",
      "youtubeUrl": "https://youtu.be/6ICtrZCHSW0?si=0ou3fp1v29o_JKKx",
      "thumbnailUrl": "https://img.youtube.com/vi/6ICtrZCHSW0/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-27 02:16:37.125114+00",
      "trackOrder": 45,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s1-53",
      "season": 1,
      "nickname": "하지",
      "title": "LÉON – Lift You Up (Official Audio)",
      "comment": "일단 들어보세요.. 기분 좋아지는 팝송 !!! ",
      "youtubeUrl": "https://youtu.be/Qv4J19gCkDg?si=cvy6tW-ENY9HO3An",
      "thumbnailUrl": "https://img.youtube.com/vi/Qv4J19gCkDg/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-03-27 14:30:33.843949+00",
      "trackOrder": 46,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s1-26",
      "season": 1,
      "nickname": "로로",
      "title": "King Gnu - BOY",
      "comment": "활기넘치는 팝과 록, 현악기의 조합이 나의 마음을 마구잡이로 휘저으며 전달하는 말: 너는 누구보다 멋져!",
      "youtubeUrl": "https://youtu.be/n0QNaym0jDI?si=chwDruVJ1bVpEJQ0",
      "thumbnailUrl": "https://img.youtube.com/vi/n0QNaym0jDI/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-23 14:21:07.876371+00",
      "trackOrder": 47,
      "voters": []
    },
    {
      "id": "s1-34",
      "season": 1,
      "nickname": "헤이즐",
      "title": "[MV] IU(아이유) _ Friday(금요일에 만나요) (Feat. Jang Yi-jeong(장이정) of HISTORY(히스토리))",
      "comment": "봄이 다가오는 지금의 느낌을 담은 곡! 요즘 많이 들어요",
      "youtubeUrl": "https://youtu.be/EiVmQZwJhsA?si=ZzGaCn8AEIeoF7kU",
      "thumbnailUrl": "https://img.youtube.com/vi/EiVmQZwJhsA/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-24 13:37:06.175901+00",
      "trackOrder": 48,
      "voters": []
    },
    {
      "id": "s1-35",
      "season": 1,
      "nickname": "하모",
      "title": "뮤지컬 데스노트 MV_The Game Begins(김준수)",
      "comment": "전율하면 김준수, 김준수 하면 전율입니다. 게임은 시작됐다. 아카데미도 시작됐다 😉",
      "youtubeUrl": "https://www.youtube.com/watch?v=aGUlfPcEyRc",
      "thumbnailUrl": "https://img.youtube.com/vi/aGUlfPcEyRc/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-24 15:17:14.895729+00",
      "trackOrder": 49,
      "voters": []
    },
    {
      "id": "s1-36",
      "season": 1,
      "nickname": "곤잘레스",
      "title": "Effie - MAKGEOLLI BANGER (Official Audio)",
      "comment": "운전하면서 들어보세여",
      "youtubeUrl": "https://youtu.be/z2DASn4UHqE?si=5-vReIjOmpVWs1d7",
      "thumbnailUrl": "https://img.youtube.com/vi/z2DASn4UHqE/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-25 01:00:21.028869+00",
      "trackOrder": 50,
      "voters": []
    },
    {
      "id": "s1-37",
      "season": 1,
      "nickname": "카를",
      "title": "星野源 – Pop Virus (Official Video)",
      "comment": "음악은 사람을 매개로 퍼져나가는 바이러스",
      "youtubeUrl": "https://youtu.be/HG0M_eZduxY?si=K_OKx_MkVCfoC6OW",
      "thumbnailUrl": "https://img.youtube.com/vi/HG0M_eZduxY/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-25 07:21:59.626917+00",
      "trackOrder": 51,
      "voters": []
    },
    {
      "id": "s1-42",
      "season": 1,
      "nickname": "소누",
      "title": "음율 - 피차일반 (彼此一般) [가사/Lyrics]",
      "comment": "꿈꾸는 걸 포기하고 싶지가 않다. 그러니까 계속 걸어가 봐야겠다.",
      "youtubeUrl": "https://www.youtube.com/watch?v=GXNTpVLMJxI",
      "thumbnailUrl": "https://img.youtube.com/vi/GXNTpVLMJxI/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-25 09:31:46.242572+00",
      "trackOrder": 52,
      "voters": []
    },
    {
      "id": "s1-52",
      "season": 1,
      "nickname": "리버",
      "title": "Parcels - Tieduprightnow (Official Music Video)",
      "comment": "날이 풀리니 parcels가 생각나요 리듬타면서 산책합시다😌",
      "youtubeUrl": "https://youtu.be/_2qsU8FGU_E?si=LB-Z5dU7t2Sn3HYb",
      "thumbnailUrl": "https://img.youtube.com/vi/_2qsU8FGU_E/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-27 03:08:18.30146+00",
      "trackOrder": 53,
      "voters": []
    },
    {
      "id": "s1-54",
      "season": 1,
      "nickname": "스타크",
      "title": "怪獣の花唄 / Vaundy ： MUSIC VIDEO",
      "comment": "밝은 멜로디, 하지만 서사가 숨어있는 가사",
      "youtubeUrl": "https://www.youtube.com/watch?v=UM9XNpgrqVk",
      "thumbnailUrl": "https://img.youtube.com/vi/UM9XNpgrqVk/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-28 13:10:18.661355+00",
      "trackOrder": 54,
      "voters": []
    },
    {
      "id": "s1-56",
      "season": 1,
      "nickname": "에린",
      "title": "GIVĒON - Heartbreak Anniversary (Audio)",
      "comment": "카페에 있는데 오랜만에 이 곡이 생각나서 올려봅니당",
      "youtubeUrl": "https://www.youtube.com/watch?v=nja_0BaQcNg&pp=ygUWaGVhcnRicmVhayBhbm5pdmVyc2FyeQ%3D%3D",
      "thumbnailUrl": "https://img.youtube.com/vi/nja_0BaQcNg/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-29 05:37:33.522191+00",
      "trackOrder": 55,
      "voters": []
    },
    {
      "id": "s1-57",
      "season": 1,
      "nickname": "케빈",
      "title": "[MV] Jang Deok Cheol(장덕철) _ See you later(있어줘요)",
      "comment": "담백한 절절함을 느끼고 싶을 때",
      "youtubeUrl": "https://www.youtube.com/watch?v=W0M8kn_Ex-4",
      "thumbnailUrl": "https://img.youtube.com/vi/W0M8kn_Ex-4/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-03-31 05:34:21.12088+00",
      "trackOrder": 56,
      "voters": []
    }
  ],
  "2": [
    {
      "id": "s2-3",
      "season": 2,
      "nickname": "스타크",
      "title": "이마트",
      "comment": "조회수 1758만, 무슨 말이 더 필요하겠는가",
      "youtubeUrl": "https://www.youtube.com/watch?v=QUXKib-jfEM",
      "thumbnailUrl": "https://img.youtube.com/vi/QUXKib-jfEM/hqdefault.jpg",
      "votes": 6,
      "createdAt": "2026-04-13 15:16:11.313723+00",
      "trackOrder": 1,
      "voters": [
        "젠틀맨",
        "1",
        "수리",
        "리버",
        "링쿠",
        "넵튠"
      ]
    },
    {
      "id": "s2-12",
      "season": 2,
      "nickname": "크리스",
      "title": "Bonvoyage",
      "comment": "러너들 앞으로의 여정이 즐거운 여행이면 좋겠어요",
      "youtubeUrl": "https://youtu.be/WNB8BUQCy-4?si=sZ4YsdSvCTUxWyLY",
      "thumbnailUrl": "https://img.youtube.com/vi/WNB8BUQCy-4/hqdefault.jpg",
      "votes": 4,
      "createdAt": "2026-04-14 04:36:50.098078+00",
      "trackOrder": 2,
      "voters": [
        "빈",
        "링쿠",
        "리버",
        "젠"
      ]
    },
    {
      "id": "s2-4",
      "season": 2,
      "nickname": "에린",
      "title": "Dominic Fike, Weezer - Think Fast (Official Audio)",
      "comment": "성큼 다가오는 여름, 어지러이 지나가는 매일, 떨치기 어려운 생각들 ",
      "youtubeUrl": "https://youtu.be/VlfAKvRpzto?si=vF0R_Xt50gR8Qc6k",
      "thumbnailUrl": "https://img.youtube.com/vi/VlfAKvRpzto/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-04-13 15:18:55.614145+00",
      "trackOrder": 3,
      "voters": [
        "젠틀맨",
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s2-6",
      "season": 2,
      "nickname": "큐",
      "title": "MARK 마크 '200' MV",
      "comment": "200OK를 기원하며",
      "youtubeUrl": "https://youtu.be/qkJ3P-9ofhE?si=wO_8P7BP24m9ThSI",
      "thumbnailUrl": "https://img.youtube.com/vi/qkJ3P-9ofhE/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-04-13 15:25:45.041634+00",
      "trackOrder": 4,
      "voters": [
        "젠틀맨",
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s2-9",
      "season": 2,
      "nickname": "메이슨",
      "title": "Gesaffelstein - Opr",
      "comment": "잡생각 끊고, 집중은 놓치지 않게 몰입을 이어지게 해주는 곡",
      "youtubeUrl": "https://youtu.be/_XhLIXjUtFg?si=4fPJ-QZyvhIqkUpP",
      "thumbnailUrl": "https://img.youtube.com/vi/_XhLIXjUtFg/hqdefault.jpg",
      "votes": 3,
      "createdAt": "2026-04-13 16:09:08.730591+00",
      "trackOrder": 5,
      "voters": [
        "젠틀맨",
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s2-7",
      "season": 2,
      "nickname": "쉐인",
      "title": "JORDANN - Café Speed (Official Music Video)",
      "comment": "새벽 2시를 넘긴, 아련한 그리움 속으로 스며드는 부드러운 몽롱함",
      "youtubeUrl": "https://youtu.be/sHOwHwdiUIU?si=NoGZ8mNg0kum2s-j",
      "thumbnailUrl": "https://img.youtube.com/vi/sHOwHwdiUIU/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-04-13 15:29:38.877334+00",
      "trackOrder": 6,
      "voters": [
        "젠틀맨",
        "링쿠"
      ]
    },
    {
      "id": "s2-10",
      "season": 2,
      "nickname": "링쿠",
      "title": "Kanye West - 옛사랑 (이문세)",
      "comment": "칸예도 이문세 님의 옛사랑을 부르면서 열심히 사는데\n나도 열심히 공부해서 성공해야지 하는 마음을 갖게 하는 곡이에요.",
      "youtubeUrl": "https://www.youtube.com/watch?v=OUI4DbnkiYs",
      "thumbnailUrl": "https://img.youtube.com/vi/OUI4DbnkiYs/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-04-14 01:06:33.471043+00",
      "trackOrder": 7,
      "voters": [
        "젠틀맨",
        "크리스"
      ]
    },
    {
      "id": "s2-13",
      "season": 2,
      "nickname": "리버",
      "title": "[MV] 까치산 (KACHISAN) - 주제는 사랑 (Theme of Love) / Official Music Video",
      "comment": "신나요 사랑합시다",
      "youtubeUrl": "https://youtu.be/RJvjoFYydCo?si=upygWZePVNDT5Ial",
      "thumbnailUrl": "https://img.youtube.com/vi/RJvjoFYydCo/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-04-14 04:44:58.205749+00",
      "trackOrder": 8,
      "voters": [
        "크리스",
        "링쿠"
      ]
    },
    {
      "id": "s2-14",
      "season": 2,
      "nickname": "빈",
      "title": "함께라서 빛난 시간",
      "comment": "함께라서 빛난 시간",
      "youtubeUrl": "https://www.youtube.com/watch?v=RAPPW_vetZ8&list=RDRAPPW_vetZ8&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/RAPPW_vetZ8/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-04-14 04:58:38.663531+00",
      "trackOrder": 9,
      "voters": [
        "크리스",
        "링쿠"
      ]
    },
    {
      "id": "s2-15",
      "season": 2,
      "nickname": "로렌",
      "title": "I Run",
      "comment": "들으면서 작업하다보면 자리를 박차고 달리고 싶게 만들수도..🏃🏃‍♀️",
      "youtubeUrl": "https://youtu.be/imQDelNtwwU?si=c9HAtNePttxXpYjh",
      "thumbnailUrl": "https://img.youtube.com/vi/imQDelNtwwU/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-04-14 06:23:03.216215+00",
      "trackOrder": 10,
      "voters": [
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s2-18",
      "season": 2,
      "nickname": "넵튠",
      "title": "Boy In Space & NOTD - Therapy (Official Video)",
      "comment": "헤드셋 끼고 듣는 거 추천함니다",
      "youtubeUrl": "https://www.youtube.com/watch?v=WnbGkSlakSI",
      "thumbnailUrl": "https://img.youtube.com/vi/WnbGkSlakSI/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-04-15 14:33:52.107782+00",
      "trackOrder": 11,
      "voters": [
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s2-5",
      "season": 2,
      "nickname": "젠틀맨",
      "title": "m-flo loves melody. & Ryohei / miss you",
      "comment": "DJ play that music louder, .... 도입부에서 논란 종결되는 추억의 노래ㅎ",
      "youtubeUrl": "https://youtu.be/KD59LJX2r38?si=BJY2CbdxUuzxw9mn",
      "thumbnailUrl": "https://img.youtube.com/vi/KD59LJX2r38/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-04-13 15:22:37.028328+00",
      "trackOrder": 12,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s2-8",
      "season": 2,
      "nickname": "수리",
      "title": "aespa 에스파 - Armageddon Demo Ver. 데모 버전",
      "comment": "케데헌의 주인공 성우 EJAE가 부른\n에스파 Armageddon 데모버전입니닷\n솔직히 전 이게 원곡보다 좋아요\n뭔가 코딩 다 부실 수 있을 것 같아요ㅎ",
      "youtubeUrl": "https://youtu.be/F1rbhDf0h68?si=Mt18qSeWd00VeMkh",
      "thumbnailUrl": "https://img.youtube.com/vi/F1rbhDf0h68/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-04-13 15:52:02.075719+00",
      "trackOrder": 13,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s2-11",
      "season": 2,
      "nickname": "레미",
      "title": "‘GAGA’ Official MV | 릴보이 (lIlBOI), pH-1, Woodie Gochild, BIG Naughty (서동현)",
      "comment": "들으면 전투력이 상승하는 느낌과 함께 리듬타면서 작업이 가능합니다.",
      "youtubeUrl": "https://www.youtube.com/watch?v=pL6KivEkjXU&list=PLN2__r66ZoivhaoiAu2Ovv52I3o3dgdKM",
      "thumbnailUrl": "https://img.youtube.com/vi/pL6KivEkjXU/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-04-14 03:47:36.691336+00",
      "trackOrder": 14,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s2-16",
      "season": 2,
      "nickname": "Craig",
      "title": "Initial D - Running In The 90s (HD)",
      "comment": "유로비트. 코드 작성이 200배 빨라집니다.",
      "youtubeUrl": "https://www.youtube.com/watch?v=kxLwGow0Tvw",
      "thumbnailUrl": "https://img.youtube.com/vi/kxLwGow0Tvw/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-04-14 06:40:51.651417+00",
      "trackOrder": 15,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s2-17",
      "season": 2,
      "nickname": "린",
      "title": "Cherry Roman Candle",
      "comment": "출근 할 때마다 듣는 노래",
      "youtubeUrl": "https://youtu.be/yYFkhUiwk4k?si=e7Nv6gxk8wvbmSZO",
      "thumbnailUrl": "https://img.youtube.com/vi/yYFkhUiwk4k/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-04-14 08:22:43.615586+00",
      "trackOrder": 16,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s2-19",
      "season": 2,
      "nickname": "프리송",
      "title": "Words",
      "comment": "이 곡을 들으면, 제가 봤던 하늘 중에 가장 별이 많던 하늘이 떠올라요!✨ 낭만 속에서 집중하고 싶을 때 자주 듣는 곡입니다.",
      "youtubeUrl": "https://www.youtube.com/watch?v=IXaMF4FqIkM&list=LL&index=4",
      "thumbnailUrl": "https://img.youtube.com/vi/IXaMF4FqIkM/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-04-17 12:48:54.283378+00",
      "trackOrder": 17,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s2-20",
      "season": 2,
      "nickname": "헤더",
      "title": "Bleachers - Rollercoaster (Audio)",
      "comment": "이 노래만 들으면 심장이 빨리 뜁니다...",
      "youtubeUrl": "https://www.youtube.com/watch?v=FmUw1MmIYvU",
      "thumbnailUrl": "https://img.youtube.com/vi/FmUw1MmIYvU/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-04-18 08:01:32.713789+00",
      "trackOrder": 18,
      "voters": []
    },
    {
      "id": "s2-21",
      "season": 2,
      "nickname": "테스터",
      "title": "[playlist] 실리카겔부터 델리스파이스까지 | 록 입문자들을 위한 국내 ROCK 30곡",
      "comment": "파도가 내리친다앙",
      "youtubeUrl": "https://youtu.be/-jVqZ1Myf80?si=hvlhEXPh-GMoa9H7",
      "thumbnailUrl": "https://img.youtube.com/vi/-jVqZ1Myf80/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-04-29 06:27:22.611102+00",
      "trackOrder": 19,
      "voters": []
    }
  ],
  "3": [
    {
      "id": "s3-2",
      "season": 3,
      "nickname": "링쿠",
      "title": "Frank Ocean - Summer Remains (Live)",
      "comment": "링쿠의 넘버 원 favorite 뮤지션 프랭크 오션의 미발표곡 Summer Remains 입니다.\n행복한 순간을 보내고 있는 듯 하지만 젊음, 현재, 지금의 관계 등에 불안을 품은듯한 가사를 노래하는 프랭크 오션에게 빠져들게되...",
      "youtubeUrl": "https://www.youtube.com/watch?v=KB_VSwJEXSE",
      "thumbnailUrl": "https://img.youtube.com/vi/KB_VSwJEXSE/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-05-07 08:52:00.993686+00",
      "time": "00:00",
      "trackOrder": 1,
      "voters": [
        "젠틀맨"
      ]
    },
    {
      "id": "s3-6",
      "season": 3,
      "nickname": "쿄조",
      "title": "선우정아 - 동거 / Kpop / Lyrics / 가사",
      "comment": "눅진합니다. 추천해요",
      "youtubeUrl": "https://www.youtube.com/watch?v=UENtsWQeJjc",
      "thumbnailUrl": "https://img.youtube.com/vi/UENtsWQeJjc/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-05-07 09:20:34.438967+00",
      "time": "00:00",
      "trackOrder": 2,
      "voters": [
        "젠틀맨",
        "프리송"
      ]
    },
    {
      "id": "s3-9",
      "season": 3,
      "nickname": "젠틀맨",
      "title": "Bill Evans - Waltz For Debby",
      "comment": "Bill Evans가 Bill Evans 했습니다.",
      "youtubeUrl": "https://youtu.be/dH3GSrCmzC8?si=aDyF1MHGDa4fUSHA",
      "thumbnailUrl": "https://img.youtube.com/vi/dH3GSrCmzC8/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-05-07 16:18:34.305403+00",
      "time": "00:00",
      "trackOrder": 3,
      "voters": [
        "프리송",
        "링쿠"
      ]
    },
    {
      "id": "s3-3",
      "season": 3,
      "nickname": "셀리나",
      "title": "[로스트아크｜OST] 꺾이지 않을 꽃 (A Tearful Blossom) / LOST ARK Official Soundtrack",
      "comment": "이 노래는 각각의 악기들이 의미하는 감정들이 있습니다. 피아노는 누군가의 눈물을 현악기는 살면서 겪는 시련과 슬픔을 뜻해 복잡한 인생을 의미하지만 플룻으로 희망을 표현합니다. 오늘 하루 수고했다고 말해주는 곡이라 추천합니다.",
      "youtubeUrl": "https://www.youtube.com/watch?v=UU9AMBuJHhk&list=RDUU9AMBuJHhk&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/UU9AMBuJHhk/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-05-07 08:54:31.756506+00",
      "time": "00:30",
      "trackOrder": 4,
      "voters": [
        "젠틀맨",
        "프리송"
      ]
    },
    {
      "id": "s3-13",
      "season": 3,
      "nickname": "로로",
      "title": "i need a band - AnnoyingBox (Performance video)",
      "comment": "오밤중에 악마가 속삭입니다... 이건 해보지 않으련?\n영감의 시간대는 으슥한 시간에 찾아오기 마련이죠.",
      "youtubeUrl": "https://youtu.be/fm-t9que3BE?si=ETDP-5o8OnuPAUos",
      "thumbnailUrl": "https://img.youtube.com/vi/fm-t9que3BE/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-05-18 16:09:56.749302+00",
      "time": "01:00",
      "trackOrder": 5,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s3-7",
      "season": 3,
      "nickname": "제스",
      "title": "K.Flay - Dreamers",
      "comment": "야경보면서 드라이브할 때 잘 어울려요",
      "youtubeUrl": "https://www.youtube.com/watch?v=T4HUIPD1LcE",
      "thumbnailUrl": "https://img.youtube.com/vi/T4HUIPD1LcE/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-05-07 10:10:01.122945+00",
      "time": "03:15",
      "trackOrder": 6,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s3-5",
      "season": 3,
      "nickname": "라나키",
      "title": "Ed Sheeran, Pokémon - Celestial [Official Video]",
      "comment": "포-켓-몬",
      "youtubeUrl": "https://www.youtube.com/watch?v=23g5HBOg3Ic&list=RD23g5HBOg3Ic&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/23g5HBOg3Ic/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-05-07 09:07:55.087413+00",
      "time": "07:30",
      "trackOrder": 7,
      "voters": [
        "젠틀맨",
        "프리송"
      ]
    },
    {
      "id": "s3-11",
      "season": 3,
      "nickname": "넵튠",
      "title": "LUCY - 못 죽는 기사와 비단 요람 (Official Lyrics Video) / ENG sub",
      "comment": "아침 출근길에 들으면 이 세상 어떤 것도 무찌를 수 있을 것만 같아요",
      "youtubeUrl": "https://www.youtube.com/watch?v=y7jrpS8GHxs",
      "thumbnailUrl": "https://img.youtube.com/vi/y7jrpS8GHxs/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-05-13 14:32:47.298304+00",
      "time": "08:50",
      "trackOrder": 8,
      "voters": [
        "링쿠"
      ]
    },
    {
      "id": "s3-8",
      "season": 3,
      "nickname": "로렌",
      "title": "Working…ish",
      "comment": "아침 잠이 덜 깼을 때, 가벼운 리듬으로 텐션 예열하기 🚀",
      "youtubeUrl": "https://youtu.be/56KV_qgAGn0?si=phft905XqYDjdS2i",
      "thumbnailUrl": "https://img.youtube.com/vi/56KV_qgAGn0/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-05-07 12:50:17.473704+00",
      "time": "10:00",
      "trackOrder": 9,
      "voters": [
        "젠틀맨",
        "프리송"
      ]
    },
    {
      "id": "s3-14",
      "season": 3,
      "nickname": "케빈",
      "title": "LUCY(루시) - 개화 (Flowering) [가사/Lyrics]",
      "comment": "활기찬 아침의 시작과 함께 들으면 좋을 것 같아요!",
      "youtubeUrl": "https://www.youtube.com/watch?v=7qvrRWMXY-8",
      "thumbnailUrl": "https://img.youtube.com/vi/7qvrRWMXY-8/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-05-27 12:14:30.084525+00",
      "time": "10:00",
      "trackOrder": 10,
      "voters": []
    },
    {
      "id": "s3-12",
      "season": 3,
      "nickname": "블레어",
      "title": "orange",
      "comment": "한낮의 햇살과 초록색 잔디, 그리고 입안 가득 퍼지는 오렌지 과즙을 소리로 옮겨 놓은 곡 🍊",
      "youtubeUrl": "https://youtu.be/B3I9dlWwyPc?si=ay3SP4Om6Hgrk8vK",
      "thumbnailUrl": "https://img.youtube.com/vi/B3I9dlWwyPc/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-05-13 15:11:27.994753+00",
      "time": "12:00",
      "trackOrder": 11,
      "voters": []
    },
    {
      "id": "s3-10",
      "season": 3,
      "nickname": "다니",
      "title": "My World",
      "comment": "출근할 때 들으면 신나요 ㅎㅎ",
      "youtubeUrl": "https://youtu.be/VHdLJa6qL4g?si=Nh5T9eTf3Hy_iQ3N",
      "thumbnailUrl": "https://img.youtube.com/vi/VHdLJa6qL4g/hqdefault.jpg",
      "votes": 1,
      "createdAt": "2026-05-08 01:19:24.467065+00",
      "time": "13:00",
      "trackOrder": 12,
      "voters": [
        "프리송"
      ]
    },
    {
      "id": "s3-15",
      "season": 3,
      "nickname": "프리송",
      "title": "Talk to You",
      "comment": "제일 뜨거운 시간! 전투력을 올려주는 노래입니다 🔥🐦‍🔥🧯",
      "youtubeUrl": "https://youtu.be/WSkJUrjpL40?si=LeFcq4K_pLHjv45k",
      "thumbnailUrl": "https://img.youtube.com/vi/WSkJUrjpL40/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-06-03 12:08:21.495437+00",
      "time": "16:00",
      "trackOrder": 13,
      "voters": []
    },
    {
      "id": "s3-4",
      "season": 3,
      "nickname": "수리",
      "title": "Justin Bieber - Red Eye (Visualizer) ft. TroyBoi",
      "comment": "1분만 들어보시면 왜 저스틴비버가 미친사람인지를 알 수 있습니다",
      "youtubeUrl": "https://www.youtube.com/watch?v=lu87waNNWlY&list=RDlu87waNNWlY&start_radio=1",
      "thumbnailUrl": "https://img.youtube.com/vi/lu87waNNWlY/hqdefault.jpg",
      "votes": 2,
      "createdAt": "2026-05-07 08:54:35.337203+00",
      "time": "20:00",
      "trackOrder": 14,
      "voters": [
        "젠틀맨",
        "프리송"
      ]
    },
    {
      "id": "s3-16",
      "season": 3,
      "nickname": "헤더",
      "title": "Justin Bieber - Hold On",
      "comment": "근본",
      "youtubeUrl": "https://youtu.be/LWeiydKl0mU?si=kAhOxcwQIYLwzpnd",
      "thumbnailUrl": "https://img.youtube.com/vi/LWeiydKl0mU/hqdefault.jpg",
      "votes": 0,
      "createdAt": "2026-06-18 05:46:26.386073+00",
      "time": "23:45",
      "trackOrder": 15,
      "voters": []
    }
  ]
} as Record<Season, Song[]>;
